app/controllers/admin/application_controller.rb, app/controllers/admin/offices_controller.rb, app/dashboards/address_dashboard.rb, app/dashboards/office_dashboard.rb, app/fields/address_field.rb, app/models/office.rb, app/policies/application_policy.rb, app/policies/office_policy.rb, app/policies/user_policy.rb, app/views/admin/offices/_form.html.haml, app/views/admin/offices/new.html.haml, app/views/fields/address_field/_form.html.haml, app/views/fields/address_field/_show.html.haml, config/routes.rb, db/migrate/20181209041046_create_offices.rb, db/schema.rb, spec/dashboards/address_dashboard_spec.rb, spec/dashboards/office_dashboard_spec.rb, spec/factories/offices.rb, spec/models/office_spec.rb, spec/policies/office_policy_spec.rb, spec/requests/admin/admin_offices_spec.rb
=> Office Model

app/controllers/application_controller.rb, app/dashboards/office_dashboard.rb, app/dashboards/user_dashboard.rb, app/helpers/application_helper.rb, app/javascript/packs/application.js, app/javascript/src/application.scss, app/models/office.rb, app/models/user.rb, app/policies/user_policy.rb, app/views/devise/invitations/new.html.haml, db/migrate/20181212062911_create_join_table_office_user.rb, db/schema.rb, package.json, spec/factories/offices.rb, spec/factories/users.rb, spec/models/user_spec.rb, spec/requests/admin/admin_users_spec.rb, spec/requests/user_invitation_spec.rb, yarn.lock
Related: #1
Adds a relationship between user & office. At least one office is required for every user. Users can assign an office when inviting a user, but they can only choose from offices that they themselves are assigned to.
Of course the admin section allows assigning any user to any office. 
It's on staging: http://omd-scheduler.herokuapp.com
=> Assign office upon invite

dev-entrypoint
Lock file may exist if prematurely exited.  Clean up in case.
=> Fix possible docker loop at entrypoint

app/controllers/admin/age_ranges_controller.rb, app/dashboards/age_range_dashboard.rb, app/models/age_range.rb, app/policies/age_range_policy.rb, config/routes.rb, db/migrate/20190107202341_create_age_ranges.rb, db/schema.rb, spec/dashboards/age_range_dashboard_spec.rb, spec/factories/age_ranges.rb, spec/models/age_range_spec.rb, spec/requests/admin/admin_age_ranges_spec.rb
This adds the `AgeRange` model, its Pundit policy, and the Administrate dashboard for it.
=> AgeRange model

.gitignore, db/seeds.rb, docker-compose.yml
=> Make admin seed user actually work

app/javascript/src/stylesheets/nav.scss, app/javascript/src/stylesheets/settings.scss, app/views/application/_nav.html.haml
Ref #20 
Improves desktop dropdown menu.
Will do mobile in a different PR
=> Better Dropdown Menu [Desktop]

package.json
This PR resolves build compilation issues for webpacker.
=> Move babel dependencies out of devDependencies

db/seeds.rb
This PR solves/references issue #55 
Pulls lists from #8 and #18
=> add db seeds

db/seeds.rb
Performs more work on #55 by cleaning up the seeds file. Also fixes a few race names that were being split into two separate names on the space that they contain as it wasn't escaped.
=> Clean up seeds file, correct race names

app/javascript/src/stylesheets/nav.scss, app/views/application/_dropdown_menu.html.haml, app/views/application/_nav.html.haml
Fixes mobile nav and maintains current desktop functionality/style
=> Mobile Nav Fixes

app/javascript/components/blockouts/RepeatInputs/index.js, app/javascript/components/blockouts/scheduler.scss, app/javascript/src/stylesheets/settings.scss
This PR solves/references issue #59
Updated modal styling to ensure the daypicker displays properly on mobile and desktop.
=> Fix Modal Daypicker

app/lib/services/need_notifications/create.rb, app/lib/services/need_notifications/update.rb, app/models/user.rb
Addresses #85 by omitting users without phone numbers from the collection of users to notify via text message.
=> Dont send text messages to users without phone number

app/controllers/admin/application_controller.rb
=> Correct spelling

db/seeds.rb
=> Add English to language seed data

app/views/devise/invitations/new.html.haml
=> Correct role label

app/controllers/needs_controller.rb, spec/controllers/needs_controller_spec.rb
=> Order needs most recently created first

app/views/needs/index.html.haml
=> Use effective_start_at on needs index

app/views/needs/show.html.haml
=> Add the need requester's name to show detail

app/models/need.rb, app/views/devise/invitations/edit.html.haml, spec/controllers/needs_controller_spec.rb
This PR solves/references issues #112 & #114
=> update checkboxes to radio buttons for medical info and felony

config/environments/production.rb, config/environments/staging.rb
Sets twilio config to test number on staging and real number in production.
=> update to new number

app/controllers/needs_controller.rb, app/views/needs/_form_fields.html.haml, spec/controllers/needs_controller_spec.rb
This PR solves/references issue #72
=> Update Need Duration UX

app/dashboards/address_dashboard.rb, app/models/address.rb, app/policies/office_policy.rb, spec/policies/office_policy_spec.rb
This PR solves/references issue #68
=> Override Address Validation

app/controllers/application_controller.rb, app/models/user.rb, app/policies/user_policy.rb
This PR solves/references issue #129
=> Permit Attributes for non-admin user updating

app/views/devise/invitations/edit.html.haml
This PR closes #144 and adds phone number field to invite edit form for all users.
=> Add Phone Number  to form for all users

app/workers/send_text_message_worker.rb, config/environments/production.rb, config/environments/staging.rb
=> update sms sending in production and base url on staging

app/models/null_objects/null_language.rb, app/views/needs/show.html.haml, spec/models/null_objects/null_language_spec.rb
This PR closes #147 and closes #145
=> Minor text changes

app/lib/services/shift_notifications/update.rb, spec/lib/services/shift_notifications/update_spec.rb, spec/spec_helper.rb
This PR solves/references issue #19
=> Shift Confirmation SMS

app/views/application/_dropdown_menu.html.haml
=> add create need link for schedulers to mobile menu

app/controllers/shifts_controller.rb, app/models/shift.rb, config/locales/en.yml, spec/requests/shifts_spec.rb
=> Prevent last shift removal

app/policies/user_policy.rb, spec/policies/user_policy_spec.rb
=> update user policy to allow social workers to invite social workers

app/models/address.rb, db/migrate/20190212201319_add_county_to_addresses.rb, db/schema.rb, db/seeds.rb, spec/factories/addresses.rb
=> Add County to Address Model

app/workers/send_text_message_worker.rb, spec/workers/send_text_message_worker_spec.rb
=> Add guard clause for nil number as stop gap solution

Gemfile, Gemfile.lock, app/models/user.rb, app/workers/send_text_message_worker.rb, spec/factories/users.rb, spec/workers/send_text_message_worker_spec.rb
We weren't doing much before. Ultimatily we'll use twillio to send a confirmation code, but this is a step in the right direction.
=> Add phone number validation

package.json, yarn.lock
This reverts commit e2afa235fcd8dc687a7121e3263daedb63e84c80.
=> Revert "Bump webpack-dev-server from 2.11.2 to 3.1.11 (#234)"

spec/rails_helper.rb, spec/support/capybara.rb
Add groups for coverage reports and silence puma startup.
=> Tweak test config

Gemfile, Gemfile.lock, app/helpers/application_helper.rb, app/models/user.rb, config/locales/en.yml, spec/helpers/application_helper_spec.rb, spec/models/user_spec.rb
Resolves #183 (as described there)
=> Add role_display method to user model

Gemfile.lock
This PR resolves the Rubyzip security issue.
=> Upgrade Rubyzip

docker-compose.mac.yml
Updates docker configuration for Mac to use the latest setup.
=> Update mac docker overlay

.circleci/config.yml, Gemfile.lock
Required running `bundle update --bundler`.
=> Upgrade bundler to 2.0.2

Gemfile, Gemfile.lock
Did some click testing and it seemed OK.
Prior PR: https://github.com/OfficeMomsandDads/scheduler/pull/269
=> Upgrade to puma 4.2.1

.babelrc, Gemfile.lock, app/views/application/_nav.html.haml, app/views/layouts/application.html.haml, bin/webpack, bin/webpack-dev-server, config/webpacker.yml, package.json, yarn.lock
I believe these are the minimal changes necessary. All tests pass and it seem to look and work fine in click testing.
=> Upgrade to Webpacker 4

Gemfile.lock
Despite being a major version change, I'm not sure it affects us. All
tests seem to pass at least.
=> Upgrade sidekiq to 6

.circleci/config.yml, docker-compose.yml
Redis 4 or later is required by Sidekiq 6.
=> Upgrade to Redis 5

.postcssrc.yml
Everything in this file appears to already be in the default new
postcss.config.js file.
=> Remove .postcssrc.yml

app/javascript/packs/application.js, babel.config.js, package.json, yarn.lock
Requires an upgrade of babel-plugin-module-resolver, and also a code change due to the removal of @babel/polyfill.
=> Use core-js 3

babel.config.js, config/webpacker.yml, package.json, yarn.lock
It seems we can resolve this same issue by just adding the components
path to resolved_paths in webpacker.yml.
=> Remove babel-plugin-module-resolver

docker/rails-entrypoint
This PR simplifies the database setup portion of the Rails service entrypoint.
=> Use Rails Database Prepare

app/helpers/admin/users_helper.rb, spec/requests/admin/admin_users_spec.rb
Let me know if you want the testing to be more specific in any way.
=> Fix/editing without phone/render edit view/issue 313

README.md
Added step by step instructions for contributing.
=> add how to contribute step by step.

app/policies/need_policy.rb, app/views/needs/_form_fields.html.haml, app/views/needs/show.html.haml, db/migrate/20191113175940_add_notes_to_needs.rb, db/schema.rb, spec/policies/need_policy_spec.rb
added a notes field for needs.
encountered an issue where one of the created needs wasn't editable. I am unsure if it is related to my changes yet. I am attempting to reproduce it.
=> Hint/enhancement/notes with need creation/issue 181

app/views/needs/_form_fields.html.haml
=> change need duration slider and field to 9 hours

app/javascript/components/NewNeedDatePicker/index.js, app/javascript/src/application.scss, package.json, yarn.lock
Only used on new need page.
react-datetime was causing an issue with the new React due to being
unmaintained.
=> Replace react-datetime with react-datepicker

app/javascript/src/stylesheets/needs.scss, app/models/need.rb, app/models/user.rb, app/policies/need_policy.rb, app/views/needs/_form_fields.html.haml, app/views/needs/office_social_workers.html.haml, app/views/needs/show.html.haml, db/migrate/20191209174202_allow_multiple_social_workers_per_need.rb, db/schema.rb, spec/policies/need_policy_spec.rb
Social workers renamed to "Child welfare workers" in the display.
=> Allow selection of multiple need social workers

app/controllers/needs_controller.rb, app/javascript/components/NeedsIndexDatePicker/index.js, app/javascript/components/NewNeedDatePicker/index.js, app/javascript/src/application.scss, app/models/need.rb, app/views/needs/index.html.haml, spec/controllers/needs_controller_spec.rb
Adds a new react component.
Renames the class in NewNeedDatePicker so they are distinguishable.
Adds a scope to Need.
Updates index method to handle presence of a start date.
Styling not completed yet.
Currently has an issue with the date being offset by one due to time zone.
=> Add date selection on needs index

.rubocop.yml, app/controllers/admin/users_controller.rb, app/controllers/verifications_controller.rb, app/helpers/admin/users_helper.rb, app/helpers/needs_helper.rb, app/models/language.rb, app/models/need.rb, app/models/shift.rb, app/policies/need_policy.rb, app/workers/remind_worker.rb, spec/controllers/application_controller_spec.rb, spec/controllers/needs_controller_spec.rb, spec/controllers/verifications_controller_spec.rb, spec/helpers/application_helper_spec.rb, spec/lib/tasks/scheduler_rake_spec.rb, spec/models/blockout_spec.rb, spec/models/need_spec.rb, spec/models/office_spec.rb, spec/models/shift_spec.rb, spec/policies/need_policy_spec.rb, spec/policies/shift_policy_spec.rb, spec/requests/shifts_spec.rb, spec/support/capybara.rb, spec/support/rake_shared_context.rb, spec/system/new_need_form_spec.rb, spec/system/responses_spec.rb, spec/workers/remind_worker_spec.rb
Many of them can be resolved appropriately, but for some I altered the configuration.
We use $twilio as a global variable in a way that seems appropriate to me;
the MethodLength and Branch Conditional sizes were a bit too restrictive.
=> Resolve all rubocop issues

app/controllers/needs_controller.rb, app/javascript/components/NewNeedDatePicker/index.js, spec/requests/needs_spec.rb
Also correct an issue where passing a null start_at would raise an
exception.
Resolves https://github.com/OfficeMomsandDads/scheduler/issues/411
=> Default need start_at to null

app/admin/users.rb, app/models/office_user.rb, app/models/user.rb, db/migrate/20200225220208_add_deactivated_to_users.rb, db/schema.rb, spec/models/office_user_spec.rb
This related to #346
This change introduces a new column to `User`: `deactivated`. In addition to this new column we provide an interface to changing the state of this column from the `ActiveAdmin` interface.
=> Allow deactivation of users

app/admin/reports.rb, app/models/office.rb, app/models/user.rb, app/views/admin/reports/_index.html.haml, app/views/admin/reports/total_volunteer_hours_by_county.csv.haml, app/views/admin/reports/total_volunteer_hours_by_office.csv.haml, app/views/admin/reports/total_volunteer_hours_by_state.csv.haml, app/views/admin/reports/total_volunteer_hours_by_user.csv.haml, app/views/admin/reports/total_volunteer_minutes_by_county.csv.haml, app/views/admin/reports/total_volunteer_minutes_by_office.csv.haml, app/views/admin/reports/total_volunteer_minutes_by_state.csv.haml, app/views/admin/reports/total_volunteer_minutes_by_user.csv.haml, spec/models/office_spec.rb, spec/models/user_spec.rb, spec/requests/admin/admin_reports_spec.rb
Resolves issue https://github.com/OfficeMomsandDads/scheduler/issues/410
=> Convert minutes to hours in reports

app/admin/site_status.rb, app/controllers/application_controller.rb, app/controllers/needs_controller.rb, spec/controllers/application_controller_spec.rb, spec/requests/needs_spec.rb
=> Allow admins to disable need creation with notice

README.md
update every instance of app with rails
=> `Update README.md

.devcontainer.json, docker-compose.yml
Changed docker-compose version from 3.7 -> 3.0 in order to support visual studio codespaces.
=> Docker & devcontainer config changes

app/models/user.rb, spec/models/user_spec.rb
=> Fix typo; add spec

app/admin/announcements.rb, app/models/announcement.rb, config/routes.rb, spec/models/announcement_spec.rb
Also, setup Sidekiq web UI and bump message limit to 1600 chars at Sarah's request.
=> Fix announcement issues

app/admin/users.rb
This PR adds filter and a column for role in the Admin. This would have been useful for recent changes during the pandemic.
=> Add filter and column for role in admin

db/migrate/20201028185930_add_receive_sms_notifications_to_users.rb, db/schema.rb
Note: branch name is spelled incorrectly.  This is a start to issue #175
=> Adds receive sms notifications to users column

app/models/need.rb, spec/lib/services/notifications/needs/recipients/create_spec.rb, spec/lib/services/notifications/needs/recipients/update_spec.rb, spec/lib/services/notifications/needs_spec.rb, spec/lib/services/notifications/shifts_spec.rb, spec/models/need_spec.rb
=> Adds creator of need to sms notifications upon need creation

app/controllers/dashboard_controller.rb, app/views/dashboard/reports.html.haml, app/views/dashboard/total_volunteer_hours_by_user_template.csv.haml, spec/requests/dashboard_spec.rb
=> Separate user name columns in hours by user report

app/lib/services/email_message_enqueue.rb, app/lib/services/notifications/needs.rb, app/lib/services/notifications/shifts.rb, app/lib/services/text_message_enqueue.rb, app/mailers/user_mailer.rb, app/models/user.rb, app/views/devise/shared/_profile_fields.html.haml, app/views/user_mailer/notification_email.html.haml, db/migrate/20201028212318_add_receive_email_notifications_to_users.rb, db/schema.rb, spec/lib/services/email_message_enqueue_spec.rb, spec/mailers/previews/user_mailer_preview.rb, spec/mailers/user_mailer_spec.rb, spec/models/user_spec.rb
=> Add Notification preferences choices for needs and shifts between SMS and email

package.json, yarn.lock
Revert webpack-cli to version 3.x
Move webpack and webpack-cli to devDependencies
Update webpack-dev-server to latest
=> Fix webpack-dev-server

.devcontainer.json, config/environments/development.rb, docker-compose.codespaces.yml, docker-compose.yml, docker/rails-entrypoint, docker/ruby/Dockerfile
The intent here is to add config for codespaces that does not break our existing docker-compose dev env setup.
Seems to work! :smile:
=> Add codespaces config

.devcontainer.json
This change allows Capybara tests to run in codespaces.
=> Add selenium to devcontainer

app/javascript/components/NewNeedDatePicker/index.js
Fixes #714 by adding a disabled property to the component if a date already exists.
=> Update to disable if data exists

config/environments/development.rb, docker-compose.yml, docker/rails-entrypoint
Puma workers reduced to 1
Docker path for PID destroy helper
=> Update Docker-compose path and puma workers

app/models/user.rb
=> Updated user.b model to format validation error correctly

app/controllers/needs_controller.rb, app/views/needs/index.html.haml, spec/controllers/needs_controller_spec.rb
Also updated header text in view to reference organization name.
Closes #830
=> Updated Needs controller, Index view, and Spec to allow schedulers to view a history of needs.

app/javascript/components/NeedChildForm/index.jsx, app/models/child.rb, app/views/needs/show.html.haml
Also change the title of the field from sex -> gender.
=> Add non-binary option to gender dropdown in need creation

app/lib/includers/shift_update_event_helper.rb, app/lib/services/notifications/needs/recipients/destroy.rb, app/models/user.rb
Specifically need delete and shift update notifications.
=> Fix bug where deactivated users are receiving notifications

.github/workflows/test.yml, Gemfile, Gemfile.lock
Implements [Selective](https://selective.ci/)™️ for use in CI to parallelize test runners, provide real-time feedback, and more.
=> Implement selective

.github/workflows/test.yml, Gemfile.lock
Bump selective-ruby-core from 0.1.2 -> 0.1.3 & use setup-selective@v1
=> Use setup-selective action

Gemfile.lock
Newer versions of Selective include some pretty compelling features such as intelligent test ordering.
=> Upgrade selective gems
