app/dashboards/office_dashboard.rb, app/dashboards/user_dashboard.rb, app/helpers/application_helper.rb, app/models/address.rb, app/models/office.rb, app/policies/office_policy.rb, app/views/fields/address_field/_index.html.haml, db/migrate/20181216033319_add_region_to_offices.rb, db/schema.rb, spec/factories/offices.rb, spec/helpers/application_helper_spec.rb, spec/models/address_spec.rb, spec/requests/admin/admin_users_spec.rb
Related: #10
Adds region to Office as an integer. Defaults to 0 which will be used as 'default/no region'.
Also adds state & region to the office select box when inviting a new user.
=> Add region to Office

config/webpacker.yml, dev-entrypoint, docker-compose.yml, docker/webpack-entrypoint
This PR adds a container running the `webpack-dev-server` for live compiling of modules and assets. It also fixes a minor setup issues with node_modules.
Please verify this does not blow up your dev env before merging.
=> Add WebpackDevServer Container

package.json
This fixes an issue with deployments. Webpacker was not available in the production environment for compiling assets because it was in the `devDependencies` only.
=> Move webpacker out of devDependencies

app/models/null_objects/null_language.rb, spec/models/null_objects/null_language_spec.rb
Addresses #71 by changing the text shown if a language isn't specified from "None" to "Not specified".
=> Alter text shown when a language isn't specified

app/models/need.rb, app/views/needs/show.html.haml, spec/factories/needs.rb, spec/lib/services/need_notifications/create_spec.rb, spec/lib/services/need_notifications/update_spec.rb, spec/lib/services/shift_notifications/create_spec.rb, spec/requests/needs_spec.rb
Addresses #81 by requiring an age range to be present when a need is created. Also adds the display of age ranges to `Needs#show` and rearranges the order of fields shown on that page (Nate agreed).
=> Require age_ranges when need created

app/models/need.rb, app/views/needs/show.html.haml, app/views/shifts/_manage_shifts.html.haml, spec/models/need_spec.rb
Addresses #69 and #77 by:
- preventing users from creating a new shift in the past
- displaying the effective start time of a need (show start time of earliest shift if it occurs before the start time of the need)
=> Show effective need start at; dont allow creating shifts in the past

app/views/admin/application/_navigation.html.erb
Addresses #67 by adding a link back to the application to the admin nav. I generated this view partial via `rails generate administrate:views:navigation`.
Also, wasn't sure what was desired for link text, so went with "Application". More than happy to change that.
=> Add link back to application from admin

app/views/devise/invitations/edit.html.haml
Addresses #79 by labeling required fields as such.
Could also alter the label text to accomplish this, but I didn't go that route. Can change if desired.
I also added the `required` input attribute to all required fields. The browser can help us out by preventing the form from being submitted if these fields are blank (will also show the user which field needs attention).
=> Add required hint text to new user form

Procfile
This uses the release feature to run migrations before the app server comes up.
=> Add release to procfile for running migration

app/models/blockout.rb
The validation would not be run in the event that the start_at was advanced
beyond the end_at.
=> Fix blockout end_at validation bug

app/lib/services/shift_notifications/update.rb
Related to [#188](https://github.com/OfficeMomsandDads/scheduler/issues/188)
- When a volunteer claims shift social workers are sent a text with full name of volunteer.
- When a volunteer releases themselves from a shift social workers are sent text with full name of the volunteer.
=> More detailed text message notifications

config/initializers/devise.rb
The old regex would allow an address like the following through:
`<teresa.huber>, <.sup@dhw.idaho.gov>`
I noticed an SMTP error in production when a user entered that address.
The new regex is one we've used on another project with good success.
=> Better email validation

.circleci/config.yml, docker-compose.yml, spec/rails_helper.rb
Fix a regression introduced when we implemented the system spec. This brings back the previous behavior while allowing system specs to run as expected.
Also, shamelessly stolen from @benjaminwood
=> Block Web Requests in Test Env

docker/rails-entrypoint
This will prevent errors when newer versions of rake are installed.
=> Add bundle exec to rails entrypoint commands

Gemfile, Gemfile.lock
The old version caused a lot of deprecation warnings and a few errors
related to the deprecation of "formats".
More info: https://github.com/rails/rails/issues/35417
=> Upgrade rspec-rails to 4.0.0.beta3

package.json, yarn.lock
It displays a warning message if you don't manually specify a core-js
version. I tried core-js@3 (the newer alternative) but got some errors.
=> Run yarn add core-js@2

package.json, yarn.lock
I previously installed the postcss-cssnext JS package with the "--dev"
flag, because that's how someone said to do it in a Github post. However
I now think it's responsible for the failures on staging and was able to
reproduce it locally. I uninstalled the --dev version and just installed
it normally and now it seems to work.
=> Install postcss-cssnext without "--dev"

.babelrc
Gets rid of a warning that the uglify key was deprecated and needs to be
replaced with this. Note that does does not go in "targets" but rather
the root level of the preset configuration.
See https://github.com/babel/babel/issues/8164
=> Replace uglify key with forceAllTransforms

.postcssrc.yml, package.json, yarn.lock
postcss-cssnext seems to work but this is the intended replacement
with Webpacker 4. It doesn't need to be added as a separate dependency
because the webpacker package requires it.
=> Replace postcss-cssnext with postcss-preset-env

.babelrc
Gets rid of a deprecation warning. I thought installing core-js fixed
it, but it needs to be specified here as well.
=> Specify corejs version in .babelrc

Gemfile, Gemfile.lock
There's not much justification to keep them locked without a breaking
new version.
Also, lock puma to '< 4.3' temporarily, just because they released a new
version just now; will update that in a subsequent PR.
=> Unlock gems with no new versions

Gemfile, Gemfile.lock
It writes a message every time we run bundle, and it doesn't really
provide any real utility, even when developing on Windows.
=> Remove tzinfo-data

config/webpacker.yml
This was causing at least one display error. It's a bit confusing to me
why they opted to make this false by default.
The same exact option is set to true in the production environment. I
opted not to remove this line, even though it's redundant, to keep as
close as possible to the webpacker defaults.
See https://github.com/rails/webpacker/pull/1625
=> Set extract_css to true on all environments

package.json, yarn.lock
Move eslint and eslint-config-hint to dev dependencies.
Add some packages to get rid of peer dependency warnings.
Upgrade some packages to get rid of peer dependency warnings.
Remove obsolete babel-core package.
Remove explicit postcss-import declaration because it is now required as a dependency of @rails/webpacker.
Fix lock on foundation-sites and upgrade it to the latest point release.
Upgrade major version of snakecase-keys.
Some warnings remain, mostly related to fsevents, but they are in packages that apparently can't be upgraded.
`yarn outdated` now shows no upgrades necessary.
=> Cleanup package.json

spec/lib/services/notifications/needs/recipients/create_spec.rb, spec/lib/services/notifications/needs/recipients/update_spec.rb, spec/lib/services/notifications/shifts/recipients/create_spec.rb
While these specs passed before, they were passing even if no blockout was
assigned, due to the age ranges not being specified on the volunteer.
=> Fix blockouts notification recipients specs

config/environments/test.rb
This is the Rails default and solves an issue related to zeitwerk
autoloading with Spring.
Resolves issue in this PR https://github.com/OfficeMomsandDads/scheduler/pull/323
=> Set cache_classes to false in test.rb

app/controllers/needs_controller.rb, app/lib/services/notifications/needs.rb, app/lib/services/notifications/shifts.rb, app/models/need.rb, spec/lib/services/notifications/needs/recipients/create_spec.rb, spec/lib/services/notifications/needs/recipients/update_spec.rb, spec/lib/services/notifications/needs_spec.rb, spec/lib/services/notifications/shifts/recipients/create_spec.rb, spec/lib/services/notifications/shifts_spec.rb
The old behavior was inconsistent and was probably causing users not to
receive desired notifications. For one thing, it only set
notified_user_ids when a need was updated; not when a need was created,
or a shift was created or updated. Second, it would exclude all future
notifications to the user once it was set, even if they would expect
them, such as needs or shifts being updated.
This commit changes that. Now, it will overwrite notified_user_ids
whenever a notification goes out related to the needs or shifts. It also
will not use notified_user_ids to exclude people from notifications.
This means that notified_user_ids is currently not being used at all
aside for as a field that is set when notifications go out. However, I
intend to use it in the future for the "users pending response" …
=> Refactor notified_user_ids

app/controllers/needs_controller.rb, app/javascript/packs/application.js, app/javascript/src/responses.js, app/models/need.rb, app/models/shift.rb, app/models/user.rb, app/policies/need_policy.rb, app/views/needs/show.html.haml, config/routes.rb, db/migrate/20191114232842_add_unavailable_users.rb, db/schema.rb, spec/controllers/needs_controller_spec.rb, spec/lib/services/notifications/needs/recipients/create_spec.rb, spec/lib/services/notifications/needs/recipients/update_spec.rb, spec/lib/services/notifications/shifts/recipients/create_spec.rb, spec/models/need_spec.rb, spec/models/shift_spec.rb, spec/models/user_spec.rb, spec/policies/need_policy_spec.rb, spec/support/devise.rb, spec/system/responses_spec.rb, spec/views/needs/show.html.haml_spec.rb
Implementation for this feature request: https://github.com/OfficeMomsandDads/scheduler/issues/212
The need show page has some new functionality. There is a "Responses" section beneath the shifts. There, notified users will be able to mark themselves as unavailable for this need. Also, admins, coordinators and social workers will be able to see who has marked themselves unavailable, as well as all notified volunteers who have not yet claimed a shift nor marked themselves unavailable.
If marked unavailable, a user will not receive any more notifications related to this need, *unless* a new shift is created. If a new shift is created, the unavailable users list is wiped clean, and users will have to mark themselves as unavailable again (or claim the new shift).
Includes some simple JS to …
=> Allow volunteers to mark themselves as unavailable

db/migrate/20191209221008_pre_verify_eligible_users.rb, db/schema.rb
This is our grandfather clause, which allows users currently on the platform to skip the verification process if they have already been receiving text messages successfully. While this doesn't ensure that they own the phone number which is receiving the messages, it's likely to satisfy the vast majority of cases. After this migration, all users will have to verify using the standard method.
This commit merely reverts an earlier commit, which itself reverts a commit, which contains the migration code.
Implements #200
=> Pre-verify user phone numbers

app/controllers/application_controller.rb, app/controllers/verifications_controller.rb, app/javascript/src/application.scss, app/javascript/src/stylesheets/verifications.scss, app/views/application/_nav.html.haml, app/views/verifications/index.html.haml, spec/controllers/application_controller_spec.rb, spec/controllers/verifications_controller_spec.rb, spec/factories/users.rb
Only affects signed in users.
Does not affect users on a Devise controller.
Does not affect users in the Verifications controller.
Now redirects to root_path upon successful verification.
Additional text added to the verify page to explain its purpose and make
it less unpleasant.
The users factory will now default verified to true.
Appropriate specs added for ApplicationController.
Implements #200
=> Make phone verification mandatory

db/seeds.rb
Marks user as verified.
Marks user as having accepted the invitation (which enables them to provide their current password on the profile edit page).
Provides a default time zone and phone number (copied from users factory data).
=> Make default admin user valid in seed data

.rubocop.yml
This solves the issue where Haml files were being run through rubocop in
Atom.
=> Explicitly exclude Haml files from Rubocop

.rubocop.yml
It's poorly suited to handle RSpec. See this discussion on the issue,
which recommends disabling this cop for specs.
https://stackoverflow.com/questions/40934345/rubocop-25-line-block-size-and-rspec-tests
=> Don't enforce Block Length cop on specs

.rubocop.yml, app/lib/includers/shift_update_event_helper.rb, app/lib/services/notifications/shifts/recipients/update.rb, app/models/office.rb, app/models/office_user.rb, app/models/user.rb, app/views/devise/shared/_profile_fields.html.haml, db/migrate/20191219190855_create_office_users.rb, db/schema.rb, spec/factories/office_users.rb, spec/lib/includers/shift_update_event_helper_spec.rb, spec/lib/services/notifications/shifts/recipients/update_spec.rb, spec/models/office_user_spec.rb, spec/models/user_spec.rb, spec/policies/user_policy_spec.rb
Implements #189.
This PR includes the following:
- The creation of a new join model, OfficeUser, which replaces the old habtm `offices_users` table. It has a boolean attribute, `send_notifications`.
- A new multi-select is added to the Edit Profile page which allows users to choose which offices they want to receive shift notifications from.
- When a shift is assigned or unassigned, notify social workers, coordinators, and admins via text message, so long as they have marked themselves as notifiable in this office. Unlike before, it will notify these users whether a shift is changed via a scheduler or the volunteer themselves.
- The Rubocop config change found in #364 
- Rubocop updates to relevant spec files.
=> Notify social workers, coordinators, and admins of shift changes, with opt-out

app/views/needs/office_social_workers.html.haml
The proper select2 CSS styling wasn't working because I didn't add the class.
It used to be impossible to set there to be NO social workers after one was set; adding a hidden field fixes that.
=> Fix some social worker selection issues

config/environments/test.rb
It's default, makes tests faster, and avoids some constant redefinition warnings.
=> Enable cache_classes in test mode

app/models/need.rb, spec/models/need_spec.rb
Midnight is the default time selection, however this time is very unlikely, so we want
to force the user to select a more appropriate time.
Add appropriate spec.
Tested in development mode.
=> Validate that start_at is not midnight

docker-compose.yml, docker/ruby/Dockerfile, package.json
Node 11 gives deprecation warnings. 12 is the current LTS version. 14 is
actually the latest version right now.
=> Upgrade to Node 12

app/models/need.rb
Ensure reminder notifications are sent only to notifiable users.
The user affected by the bug @nshoes fixed in #523 received a reminder notification around noon today. This should fix that!
=> Filter notifiable users in reminder notifications

app/models/need.rb
We can't use find here. If one of the users is excluded by the notifiable scope, we'll get a record not found error.
=> Hotfix for users_pending_response

app/models/office.rb, spec/models/office_spec.rb
We need distinct in the query because of the join. Otherwise, we end up with wild, obviously incorrect numbers.
=> Fix total volunteers by race report

Gemfile, Gemfile.lock
Adds OSS license key for mutant. This key is only useful for this repository, so no danger it exposing it in Gemfile (Mutant does the same](https://github.com/mbj/mutant/blob/master/Gemfile.shared#L4).
=> Add mutant license key

app/javascript/components/NewNeedDatePicker/index.js, app/views/needs/_form_fields.html.haml
Fixes a bug when creating a new need with validation errors. Previously, if an error prevented the need from saving the date/time would not be editable. This fix checks to see if the need being created/edited exists and only allows modifying date/time if the need does not exist.
=> Add check for existing need

db/migrate/20220215192557_add_children_to_existing_needs_take_two.rb, db/schema.rb
The previous migration called `number_of_children`, which was redefined to count Child records. This effectively ensured that the migration had no effect.
=> Add children to existing needs - take two

app/javascript/src/stylesheets/needs.scss
This fixes an issue where some shifts would not be visible because the text is white on a white background.
I suspect we may have another issue or two like this that needs to be resolved.
=> Adjust colors after rebranding update

.gitignore, docker-compose.codespaces.yml
This fixes the issue, where when initializing workspace within the docker container for the first time, docker-compose.codespace.yml reference the volume /app rather than /workspace/scheduler. So the working terminal does not start in the root directory.
=> Updated docker-compose codespace to reference workspace rather than app

config/initializers/sidekiq.rb
This fixes the issue, where shift surveys were not being sent due to https://github.com/fosterful/scheduler/blob/abc31a7903ef659ab628f74da68a008a8c9d0af9/config/initializers/sidekiq.rb#L19 returning an empty job instead of nil, preventing the creation of the cron job.
All test passed with Rspec, but still getting 66.67% coverage with Spring.
The neat thing about the implementation is that, if the jobs do not exist, they are created, if they already exist they are updated and if there are jobs running, it will remove them if not present in the given array.
This closes Issue #806
=> Updated config initializer for sidekiq to use #load_from_array

config/initializers/sidekiq.rb
As it turns out, '0 5,20,35,50 * ? * *' is not a valid cron expression. This has been wrong since it was committed last year.
We improved the shift selection process such that it doesn't matter how frequently we run the job. So, I've simplified it to every 5 minutes here.
=> Fix Shift Surveys cron schedule

config/environments/staging.rb
Fixed url references staging, by switching to ENV var the url can be set at each Heroku environment.
Closes #819
=> Created Demo ENV and fixed env staging to reference url as ENV vars

app/lib/services/notifications/shifts/message/update.rb, spec/lib/services/notifications/shifts/message/update_spec.rb
Quick adjustment to remove the proof of vaccination message.
=> Remove proof of vax message

app/controllers/application_controller.rb
Per the Heroku docs, they use self-signed certs.
https://devcenter.heroku.com/articles/connecting-heroku-redis#connecting-in-rails
=> Fix redis SSL error

Gemfile.lock
Bump to the latest version of selective-ruby-core.
=> Upgrade selective-ruby-core to 0.1.2
